site_name: Open Health-Context

pages:
    - Home: index.md
    - Introduction: introduction.md
    - Mobile Application: application.md
    - Dashboard: dashboard.md
    - Architecture: architecture.md

theme: readthedocs